import { Project, Chapter } from '@/types';

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Футбол: Максимальный Уровень Приёма Мяча',
    rulateUrl: 'https://tl.rulate.ru/book/12345',
    sourceUrl: 'https://example.com/novel',
    createdAt: '2025-12-25',
    status: 'in_progress',
    totalChapters: 422,
    translatedChapters: 321,
    views: 1287,
    bookmarks: 6,
    income: 0,
  },
  {
    id: '2',
    title: 'Онлайн-игра: Мои Призывы Работают, а я Отдыхаю',
    rulateUrl: 'https://tl.rulate.ru/book/12346',
    sourceUrl: 'https://example.com/novel2',
    createdAt: '2025-12-25',
    status: 'in_progress',
    totalChapters: 549,
    translatedChapters: 549,
    views: 1287,
    bookmarks: 20,
    income: 4.74,
  },
  {
    id: '3',
    title: 'Безумный Фарм Новый Способ Заработка Каждый День',
    rulateUrl: 'https://tl.rulate.ru/book/12347',
    sourceUrl: 'https://example.com/novel3',
    createdAt: '2025-12-22',
    status: 'in_progress',
    totalChapters: 926,
    translatedChapters: 393,
    views: 897,
    bookmarks: 21,
    income: 0,
  },
];

export const mockChapters: Chapter[] = [
  {
    id: 'ch1',
    projectId: '1',
    number: 1,
    title: '第1章 我的系统',
    originalText: '这是第一章的内容...',
    status: 'translated',
    createdAt: '2025-12-27',
  },
  {
    id: 'ch2',
    projectId: '1',
    number: 2,
    title: '第2章 爱有时候是痛苦的',
    originalText: '这是第二章的内容...',
    status: 'translated',
    createdAt: '2025-12-27',
  },
  {
    id: 'ch3',
    projectId: '1',
    number: 3,
    title: '第3章 只要主人说那个人必须死，结的拳头就不会停',
    originalText: '这是第三章的内容...',
    status: 'pending',
    createdAt: '2025-12-27',
  },
  {
    id: 'ch4',
    projectId: '1',
    number: 4,
    title: '第4章 假证',
    originalText: '这是第四章的内容...',
    status: 'pending',
    createdAt: '2025-12-27',
  },
  {
    id: 'ch5',
    projectId: '1',
    number: 5,
    title: '第5章 毁尸灭迹',
    originalText: '这是第五章的内容...',
    status: 'pending',
    createdAt: '2025-12-27',
  },
  {
    id: 'ch6',
    projectId: '1',
    number: 6,
    title: '第6章 我还真是个坏人',
    originalText: '这是第六章的内容...',
    status: 'pending',
    createdAt: '2025-12-27',
  },
];
